version : "3"

services:
  mongo_db :
    container_name : database_container
    image: mongo:latest
    restart: always
    volume:
      - mongo_db:/data/db

app:
  build: .
  ports:
    - 3001:3000
  environment:
    APP_NAME: LearnDocker
    PORT: 3000
    DB_URI : mongodb://localhost:27017/crud
  depends_on:
    - mongo_db

volumes:
  mongo_db: {}